#############################################################################
# Makefile for building: FaceRec
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Dec 6 19:59:56 2012
# Project:  FaceRec.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile FaceRec.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu /usr/lib/libopencv_core.so /usr/lib/libopencv_highgui.so /usr/lib/libopencv_imgproc.so /usr/lib/libopencv_objdetect.so -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = webcamImagePaint.cpp \
		verifier.cpp \
		utils.cpp \
		tracker.cpp \
		qtUtils.cpp \
		opencvWebcam.cpp \
		faceDetector.cpp \
		eyesDetector.cpp \
		detector.cpp \
		mainwindow.cpp \
		main.cpp \
		usermanager.cpp moc_mainwindow.cpp \
		moc_faceTrainer.cpp \
		moc_aboutBox.cpp \
		moc_faceTrainerAdvSettings.cpp \
		qrc_graphics.cpp
OBJECTS       = webcamImagePaint.o \
		verifier.o \
		utils.o \
		tracker.o \
		qtUtils.o \
		opencvWebcam.o \
		faceDetector.o \
		eyesDetector.o \
		detector.o \
		mainwindow.o \
		main.o \
		usermanager.o \
		moc_mainwindow.o \
		moc_faceTrainer.o \
		moc_aboutBox.o \
		moc_faceTrainerAdvSettings.o \
		qrc_graphics.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		FaceRec.pro
QMAKE_TARGET  = FaceRec
DESTDIR       = 
TARGET        = FaceRec

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_faceTrainerAdvSettings.h ui_faceTrainer.h ui_faceAuth.h ui_aboutDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FaceRec.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile FaceRec.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile FaceRec.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/FaceRec1.0.0 || $(MKDIR) .tmp/FaceRec1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FaceRec1.0.0/ && $(COPY_FILE) --parents verifier.h utils.h tracker.h qtUtils.h opencvWebcam.h faceDetector.h eyesDetector.h detector.h webcamImagePaint.h mainwindow.h faceTrainer.h aboutBox.h faceTrainerAdvSettings.h usermanager.h pam_face_defines.h pam_face_authentication.h .tmp/FaceRec1.0.0/ && $(COPY_FILE) --parents graphics.qrc .tmp/FaceRec1.0.0/ && $(COPY_FILE) --parents webcamImagePaint.cpp verifier.cpp utils.cpp tracker.cpp qtUtils.cpp opencvWebcam.cpp faceDetector.cpp eyesDetector.cpp detector.cpp mainwindow.cpp main.cpp usermanager.cpp .tmp/FaceRec1.0.0/ && $(COPY_FILE) --parents mainwindow.ui faceTrainerAdvSettings.ui faceTrainer.ui faceAuth.ui aboutDialog.ui .tmp/FaceRec1.0.0/ && (cd `dirname .tmp/FaceRec1.0.0` && $(TAR) FaceRec1.0.0.tar FaceRec1.0.0 && $(COMPRESS) FaceRec1.0.0.tar) && $(MOVE) `dirname .tmp/FaceRec1.0.0`/FaceRec1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FaceRec1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_faceTrainer.cpp moc_aboutBox.cpp moc_faceTrainerAdvSettings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_faceTrainer.cpp moc_aboutBox.cpp moc_faceTrainerAdvSettings.cpp
moc_mainwindow.cpp: opencvWebcam.h \
		detector.h \
		tracker.h \
		pam_face_defines.h \
		faceDetector.h \
		eyesDetector.h \
		verifier.h \
		usermanager.h \
		webcamImagePaint.h \
		qtUtils.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_faceTrainer.cpp: ui_faceTrainer.h \
		faceTrainerAdvSettings.h \
		ui_faceTrainerAdvSettings.h \
		opencvWebcam.h \
		detector.h \
		tracker.h \
		pam_face_defines.h \
		faceDetector.h \
		eyesDetector.h \
		verifier.h \
		usermanager.h \
		faceTrainer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) faceTrainer.h -o moc_faceTrainer.cpp

moc_aboutBox.cpp: ui_aboutDialog.h \
		aboutBox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aboutBox.h -o moc_aboutBox.cpp

moc_faceTrainerAdvSettings.cpp: ui_faceTrainerAdvSettings.h \
		opencvWebcam.h \
		detector.h \
		tracker.h \
		pam_face_defines.h \
		faceDetector.h \
		eyesDetector.h \
		verifier.h \
		usermanager.h \
		faceTrainerAdvSettings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) faceTrainerAdvSettings.h -o moc_faceTrainerAdvSettings.cpp

compiler_rcc_make_all: qrc_graphics.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_graphics.cpp
qrc_graphics.cpp: graphics.qrc \
		logo3.png \
		logo2.gif \
		logo.gif
	/usr/bin/rcc -name graphics graphics.qrc -o qrc_graphics.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_faceTrainerAdvSettings.h ui_faceTrainer.h ui_faceAuth.h ui_aboutDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_faceTrainerAdvSettings.h ui_faceTrainer.h ui_faceAuth.h ui_aboutDialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_faceTrainerAdvSettings.h: faceTrainerAdvSettings.ui
	/usr/bin/uic-qt4 faceTrainerAdvSettings.ui -o ui_faceTrainerAdvSettings.h

ui_faceTrainer.h: faceTrainer.ui
	/usr/bin/uic-qt4 faceTrainer.ui -o ui_faceTrainer.h

ui_faceAuth.h: faceAuth.ui
	/usr/bin/uic-qt4 faceAuth.ui -o ui_faceAuth.h

ui_aboutDialog.h: aboutDialog.ui
	/usr/bin/uic-qt4 aboutDialog.ui -o ui_aboutDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

webcamImagePaint.o: webcamImagePaint.cpp webcamImagePaint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o webcamImagePaint.o webcamImagePaint.cpp

verifier.o: verifier.cpp verifier.h \
		usermanager.h \
		pam_face_defines.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o verifier.o verifier.cpp

utils.o: utils.cpp pam_face_defines.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

tracker.o: tracker.cpp tracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tracker.o tracker.cpp

qtUtils.o: qtUtils.cpp pam_face_defines.h \
		qtUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtUtils.o qtUtils.cpp

opencvWebcam.o: opencvWebcam.cpp opencvWebcam.h \
		pam_face_defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opencvWebcam.o opencvWebcam.cpp

faceDetector.o: faceDetector.cpp faceDetector.h \
		tracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faceDetector.o faceDetector.cpp

eyesDetector.o: eyesDetector.cpp eyesDetector.h \
		pam_face_defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eyesDetector.o eyesDetector.cpp

detector.o: detector.cpp detector.h \
		tracker.h \
		pam_face_defines.h \
		faceDetector.h \
		eyesDetector.h \
		utils.h \
		qtUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detector.o detector.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		opencvWebcam.h \
		detector.h \
		tracker.h \
		pam_face_defines.h \
		faceDetector.h \
		eyesDetector.h \
		verifier.h \
		usermanager.h \
		webcamImagePaint.h \
		qtUtils.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

main.o: main.cpp faceTrainer.h \
		ui_faceTrainer.h \
		faceTrainerAdvSettings.h \
		ui_faceTrainerAdvSettings.h \
		opencvWebcam.h \
		detector.h \
		tracker.h \
		pam_face_defines.h \
		faceDetector.h \
		eyesDetector.h \
		verifier.h \
		usermanager.h \
		aboutBox.h \
		ui_aboutDialog.h \
		webcamImagePaint.h \
		utils.h \
		qtUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

usermanager.o: usermanager.cpp usermanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usermanager.o usermanager.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_faceTrainer.o: moc_faceTrainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_faceTrainer.o moc_faceTrainer.cpp

moc_aboutBox.o: moc_aboutBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutBox.o moc_aboutBox.cpp

moc_faceTrainerAdvSettings.o: moc_faceTrainerAdvSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_faceTrainerAdvSettings.o moc_faceTrainerAdvSettings.cpp

qrc_graphics.o: qrc_graphics.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_graphics.o qrc_graphics.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

